#!/usr/bin/env pwsh
#Requires -Version 7.0
# install-privacy-guard.ps1 — install an untracked pre-commit hook that blocks a private
# pattern (typically a real personal name) in staged additions, staged filenames, or the
# commit identity. See the RepoKit standard, "Author identity".
#
# Why an installer instead of a tracked hook: the guard patterns are the secret — they must
# never enter the tree. This script is clean and trackable; the patterns live only in
# .git/hooks/, which git never commits and never clones.
#
# Patterns are case-insensitive LITERAL substrings, not regexes — the hand-rolled guard this
# replaces failed silently on a regex quoting subtlety (GNU BRE "\+"), passing everything it
# was meant to block. Literals cannot fail that way, and a literal is exactly what a name is.
#
# Every install ends with an automatic negative test in a throwaway fixture repo: a clean
# stage must pass, and a synthetic content leak, filename leak, and real-name identity must
# each be blocked. If any assertion fails the hook is removed again — a guard that has never
# failed a negative test is not yet a guard.
#
# The hook does not travel with clones — re-run this installer on every clone/machine. And
# `git commit --no-verify` bypasses any pre-commit hook, so keep the CI-side guards too.
#
# Usage:
#   pwsh scripts/install-privacy-guard.ps1                        # prompts for patterns
#   pwsh scripts/install-privacy-guard.ps1 -Pattern 'Ann,Doe'     # non-interactive, comma-separated
#   pwsh scripts/install-privacy-guard.ps1 -SkipIdentityCheck     # repo has a declared identity variance
#   pwsh scripts/install-privacy-guard.ps1 -Force                 # replace a foreign pre-commit hook
# A comma always separates patterns (so the flag survives every calling shell); a comma can
# therefore not be part of a pattern.
# Exit code: 0 = installed and negative test passed, 1 = refused or negative test failed.

[CmdletBinding()]
param(
    [string[]]$Pattern,
    [switch]$SkipIdentityCheck,
    [switch]$Force,
    [string]$RepoRoot = '.'
)

$ErrorActionPreference = 'Stop'

function Die([string]$msg) { Write-Host "privacy-guard: $msg"; exit 1 }

# --- Locate the repo and its hooks directory -------------------------------------------------
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
git -C $RepoRoot rev-parse --git-dir *> $null
if ($LASTEXITCODE -ne 0) { Die "not a git repository: $RepoRoot" }

# A configured core.hooksPath may point INSIDE the working tree (e.g. a tracked .husky/) —
# installing there would commit the very patterns this guard exists to keep out of the tree.
$customHooks = git -C $RepoRoot config --get core.hooksPath
if ($customHooks) {
    Die "core.hooksPath is set ('$customHooks') - refusing to install where the patterns could be tracked. Unset it, or extend that hook chain by hand."
}

$hooksDir = git -C $RepoRoot rev-parse --git-path hooks
if (-not [IO.Path]::IsPathRooted($hooksDir)) { $hooksDir = Join-Path $RepoRoot $hooksDir }
New-Item -ItemType Directory -Force -Path $hooksDir | Out-Null

# --- Gather the patterns (never written anywhere but .git/hooks/) ----------------------------
if (-not $Pattern -or $Pattern.Count -eq 0) {
    Write-Host 'Enter the private patterns to block (case-insensitive literal text - a first name,'
    Write-Host 'a last name, a personal username). They are stored only in .git/hooks/, never in the tree.'
    $Pattern = @()
    while ($true) {
        $p = Read-Host "Pattern $($Pattern.Count + 1) (blank to finish)"
        if ([string]::IsNullOrWhiteSpace($p)) { break }
        $Pattern += $p
    }
}
$Pattern = @($Pattern | ForEach-Object { $_ -split ',' } | ForEach-Object { $_.Trim() } |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)
if ($Pattern.Count -eq 0) { Die 'no patterns given - nothing to guard.' }

# --- Refuse to clobber a hook that is not ours -----------------------------------------------
$marker    = 'repokit privacy-guard'
$shimPath  = Join-Path $hooksDir 'pre-commit'
$guardPath = Join-Path $hooksDir 'pre-commit-privacy-guard.ps1'

if ((Test-Path -LiteralPath $shimPath) -and -not $Force) {
    if ((Get-Content -LiteralPath $shimPath -Raw) -notmatch [regex]::Escape($marker)) {
        Die "a pre-commit hook already exists at $shimPath and is not this guard - merge by hand, or re-run with -Force to replace it."
    }
}

# --- Compose the guard -----------------------------------------------------------------------
# Block messages name the pattern by INDEX only, so a pasted hook transcript never spells the
# secret it guards.
$guardTemplate = @'
# repokit privacy-guard — generated by scripts/install-privacy-guard.ps1. UNTRACKED on
# purpose: the patterns below are exactly what the tree must never contain. Never commit
# this file; re-run the installer on each clone.
$ErrorActionPreference = 'Stop'
Set-Location (git rev-parse --show-toplevel)
$patterns = @(__PATTERNS__)

$script:hits = 0
function Hit([string]$msg) { Write-Host "privacy-guard: $msg"; $script:hits++ }

# On an unborn branch (first commit) diff against the empty tree.
git rev-parse --verify --quiet HEAD *> $null
if ($LASTEXITCODE -eq 0) {
    $base = 'HEAD'
} else {
    $base = @() | git mktree
    if ($LASTEXITCODE -ne 0 -or -not $base) { $base = '4b825dc642cb6eb9a060e54bf8d69288fbee4904' }
}

# 1. Staged content — added lines only ("+" but not the "+++" file header).
$file = ''
foreach ($line in @(git diff --cached $base --no-color --unified=0 --diff-filter=ACMR)) {
    if ($line.StartsWith('+++')) { $file = $line -replace '^\+\+\+ (b/)?', ''; continue }
    if (-not $line.StartsWith('+')) { continue }
    for ($i = 0; $i -lt $patterns.Count; $i++) {
        if ($line.IndexOf($patterns[$i], [StringComparison]::OrdinalIgnoreCase) -ge 0) {
            Hit "staged addition in '$file' matches blocked pattern $($i + 1)"
        }
    }
}

# 2. Staged paths — a leak can live in a filename, not just in content.
foreach ($name in @(git diff --cached $base --name-only --diff-filter=ACMR)) {
    for ($i = 0; $i -lt $patterns.Count; $i++) {
        if ($name.IndexOf($patterns[$i], [StringComparison]::OrdinalIgnoreCase) -ge 0) {
            Hit "staged path '$name' matches blocked pattern $($i + 1)"
        }
    }
}
__IDENTITY_CHECK__
if ($script:hits -gt 0) {
    Write-Host "privacy-guard: commit blocked ($script:hits finding(s))."
    Write-Host 'privacy-guard: unstage the leak first; --no-verify bypasses this hook if you are certain.'
    exit 1
}
exit 0
'@

$identityBlock = @'

# 3. Commit identity — handle + noreply in both fields (the standard, "Author identity").
$idName  = git config user.name
$idEmail = git config user.email
$idOk = $false
if ($idEmail -eq 'noreply@github.com') { $idOk = ($idName -eq 'GitHub') }
elseif ($idEmail -match '^(\d+\+)?(?<login>[^@]+)@users\.noreply\.github\.com$') { $idOk = ($idName -eq $Matches['login']) }
if (-not $idOk) { Hit "commit identity is not handle + noreply: $idName <$idEmail>" }
'@
if ($SkipIdentityCheck) { $identityBlock = '' }

$patternList = ($Pattern | ForEach-Object { "'" + ($_ -replace "'", "''") + "'" }) -join ', '
$guardContent = $guardTemplate.Replace('__PATTERNS__', $patternList).Replace('__IDENTITY_CHECK__', $identityBlock)

# The shim must be LF-only and executable — git runs it through sh.
$shimContent = "#!/bin/sh`n# $marker shim - do not commit; installed by scripts/install-privacy-guard.ps1`nexec pwsh -NoProfile -File `"`$(git rev-parse --git-path hooks)/pre-commit-privacy-guard.ps1`"`n"

[IO.File]::WriteAllText($guardPath, $guardContent)
[IO.File]::WriteAllText($shimPath, $shimContent)
if (-not $IsWindows) { chmod +x $shimPath }

# --- Negative test: the guard must fail before it may pass -----------------------------------
# Runs in a throwaway fixture repo so the user's index is never touched. The fixture starts
# with no commits, which also exercises the unborn-branch diff base.
function Invoke-Guard([string]$Dir) {
    Push-Location $Dir
    try { & pwsh -NoProfile -File $guardPath *> $null; return $LASTEXITCODE }
    finally { Pop-Location }
}

$sample  = $Pattern[0]
$fixture = Join-Path ([IO.Path]::GetTempPath()) ("repokit-privacy-guard-selftest-" + [guid]::NewGuid())
New-Item -ItemType Directory -Path $fixture | Out-Null
try {
    git -C $fixture init -q -b main 2>$null
    if ($LASTEXITCODE -ne 0) { git -C $fixture init -q; git -C $fixture branch -m main }   # git < 2.28
    git -C $fixture config core.autocrlf false
    git -C $fixture config commit.gpgsign false
    git -C $fixture config user.name  'octocat'
    git -C $fixture config user.email 'octocat@users.noreply.github.com'

    # (a) A clean stage must PASS — a guard that always blocks proves nothing.
    Set-Content -LiteralPath (Join-Path $fixture 'clean.txt') -Value 'nothing private here'
    git -C $fixture add -A
    if ((Invoke-Guard $fixture) -ne 0) { throw 'the guard blocked a clean stage' }

    # (b) A staged content leak must be BLOCKED.
    Set-Content -LiteralPath (Join-Path $fixture 'leak.txt') -Value "synthetic leak: $sample"
    git -C $fixture add -A
    if ((Invoke-Guard $fixture) -eq 0) { throw 'the guard passed a staged content leak' }
    git -C $fixture rm -q --cached leak.txt
    Remove-Item -LiteralPath (Join-Path $fixture 'leak.txt')

    # (c) A leak in a staged FILENAME must be blocked (testable when the pattern is filename-safe).
    if ($sample -match '^[A-Za-z0-9 ._-]+$') {
        $leakName = "about-$sample.txt"
        Set-Content -LiteralPath (Join-Path $fixture $leakName) -Value 'content clean, name leaks'
        git -C $fixture add -A
        if ((Invoke-Guard $fixture) -eq 0) { throw 'the guard passed a staged filename leak' }
        git -C $fixture rm -q --cached -- $leakName
        Remove-Item -LiteralPath (Join-Path $fixture $leakName)
    } else {
        Write-Host 'privacy-guard: pattern 1 is not filename-safe - the filename check was exercised by the content case only'
    }

    # (d) With identity enforcement on, a real-name identity must be BLOCKED.
    if (-not $SkipIdentityCheck) {
        git -C $fixture config user.name 'Ann Example'
        if ((Invoke-Guard $fixture) -eq 0) { throw 'the guard passed a real-name commit identity' }
        git -C $fixture config user.name 'octocat'
    }
} catch {
    Remove-Item -Force -ErrorAction SilentlyContinue $shimPath, $guardPath
    Die "NEGATIVE TEST FAILED - $($_.Exception.Message). The hook has been removed; do not trust it, investigate before re-installing."
} finally {
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $fixture
}

# --- Summary ---------------------------------------------------------------------------------
$identityNote = if ($SkipIdentityCheck) { 'off' } else { 'on' }
Write-Host "privacy-guard: negative test passed - the hook blocked every synthetic leak before passing."
Write-Host "privacy-guard: installed at $shimPath ($($Pattern.Count) pattern(s), identity check $identityNote)."
Write-Host 'privacy-guard: hooks do not travel with clones - re-run this installer on each machine.'
